title: PoiTaro
url: "https://poitaro.com"
plugins:
  - jekyll-sitemap

# Exclude common non-site files from the Jekyll build
exclude:
  - node_modules
  - .github
  - scripts
  - thumbnails
  - articles
